USE [COMICS]
GO

CREATE TABLE READING_LIST 
(
	ID					DECIMAL (15, 0) IDENTITY (1, 1) NOT NULL,
	ACTIVE				BIT								NOT NULL,
	DATE_OF_INSERTION	DATETIME						NOT NULL,
	COMIC_ID			VARCHAR (256)					NOT NULL,
	[USER_ID]			NUMERIC (15, 0)					NOT NULL,
	[READ]				BIT								NOT NULL	
	CONSTRAINT PK_READING_LIST PRIMARY KEY (ID)
)
GO

ALTER TABLE READING_LIST
ADD CONSTRAINT FK_READING_LIST_USERS
FOREIGN KEY ([USER_ID]) REFERENCES USERS(ID)