USE [COMICS]
GO

CREATE TABLE [USERS]
(
	ID			NUMERIC (15, 0) IDENTITY (1, 1) NOT NULL,
	ACTIVE		BIT								NOT NULL,
	[USERNAME]	VARCHAR (30)					NOT NULL,
	[NAME]		VARCHAR (255)					NOT NULL,
	[PASSWORD] 	VARCHAR (512)					NOT NULL,
	CONSTRAINT PK_USER PRIMARY KEY (ID)
)
GO